main: com.zuhairparvez.customdurability.Main
name: CustomDurability
version: 1.0.1
author: Zuhair Parvez
api-version: 1.14

commands:
    durability:
        description: Command to show actual and custom damages of the item in primary hand
        usage: /durability [playerName]